# -*- coding: utf-8 -*-
"""22670136_BERT Embedding + Clustering Persepsi Masyarakat_NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gs60265W3US0OZT5epyMlgOEeUTfzdG

# **TAHAP 1 — Persiapan Lingkungan**
"""

!pip install transformers sentence-transformers umap-learn hdbscan pandas numpy matplotlib seaborn

"""# **TAHAP 2 — Load Dataset dari Apify**"""

import pandas as pd

df = pd.read_excel("youtube_comments.xlsx")

df.head()

df = df.dropna(subset=["author"])

df.head()

import re

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s.,!?]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


df["comment"] = df["comment"].astype(str)

df["clean_text"] = df["comment"].apply(clean_text)
df.head()

"""# **TAHAP 4 — Generate Embedding dengan IndoBERT / Sentence-BERT**

* Sentence-BERT multilingual
"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

embeddings = model.encode(df["clean_text"].tolist(), show_progress_bar=True)

"""# **TAHAP 5 — Dimensionality Reduction dengan UMAP**

UMAP sangat cocok untuk:

* text embedding

* clustering + visualisasi
"""

import umap

umap_model = umap.UMAP(
    n_neighbors=15,
    n_components=2,
    min_dist=0.1,
    metric='cosine',
    random_state=42
)

umap_embeddings = umap_model.fit_transform(embeddings)

"""# **TAHAP 6 — Clustering dengan HDBSCAN**

* Tidak perlu menentukan jumlah cluster

* Bisa menangani data noisy

* Bisa menghasilkan cluster "besar" dan "kecil"
"""

import hdbscan

clusterer = hdbscan.HDBSCAN(
    min_cluster_size=15,
    metric='euclidean',
    cluster_selection_method='eom'
)

df["cluster"] = clusterer.fit_predict(umap_embeddings)

"""# **TAHAP 7 — Menampilkan Jumlah Cluster**"""

df["cluster"].value_counts()

"""# **TAHAP 8 — Interpretasi Setiap Cluster**
* lihat isi komentar di tiap cluster
"""

def show_cluster(n, sample=100):
    print(f"--- Cluster {n}  ---")
    display(df[df["cluster"] == n]["clean_text"].head(sample))

show_cluster(0)
show_cluster(1)
show_cluster(2)
show_cluster(-1)

"""# **TAHAP 9 — Visualisasi Clustering (Grafik 2D)**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.scatter(umap_embeddings[:,0], umap_embeddings[:,1],
            c=df["cluster"], s=10)
plt.title("Clustering Persepsi Masyarakat Menggunakan BERT Embedding + UMAP + HDBSCAN")
plt.show()

df.to_csv("clustered_comments.csv", index=False)

"""**TAHAP 10 — Ekstraksi Kata Dominan per Cluster**

* TF-IDF untuk mengekstrak keyword per cluster.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

def get_top_keywords(cluster_id, n_keywords=10):
    texts = df[df["cluster"] == cluster_id]["clean_text"].tolist()

    vectorizer = TfidfVectorizer(stop_words='indonesian', max_features=3000)
    tfidf = vectorizer.fit_transform(texts)

    scores = np.asarray(tfidf.sum(axis=0)).ravel().tolist()
    vocab = vectorizer.get_feature_names_out()

    top_idx = np.argsort(scores)[::-1][:n_keywords]
    top_keywords = [vocab[i] for i in top_idx]

    return top_keywords


clusters = sorted(df["cluster"].unique())

for c in clusters:
    if c != -1:
        print(f"\n=== Cluster {c} ===")
        print(get_top_keywords(c))

"""**TAHAP 11 — Menampilkan Komentar Paling Representatif (Centroid Nearest Comments)**

* Komentar paling representatif = komentar paling dekat dengan pusat cluster.
"""

import numpy as np

def get_representative_comments(cluster_id, top_n=5):
    idxs = df[df["cluster"] == cluster_id].index.tolist()
    cluster_embeds = embeddings[idxs]

    centroid = cluster_embeds.mean(axis=0)

    distances = np.linalg.norm(cluster_embeds - centroid, axis=1)
    top_idxs = distances.argsort()[:top_n]

    representative = df.iloc[[idxs[i] for i in top_idxs]]["clean_text"].tolist()
    return representative


get_representative_comments(cluster_id=0, top_n=5)

"""**TAHAP 12 — Menyimpulkan TOPIK PERSEPSI OTOMATIS (Heuristic Labeling)**"""

def label_topic(keywords):
    kw = " ".join(keywords)

    if any(k in kw for k in ["bingung", "gimana", "ribet", "pusing"]):
        return "Kebingungan Masyarakat"
    if any(k in kw for k in ["setuju", "baik", "mendukung", "bagus"]):
        return "Dukungan Terhadap Kebijakan"
    if any(k in kw for k in ["mahal", "inflasi", "harga", "naik"]):
        return "Kekhawatiran Inflasi / Harga"
    if any(k in kw for k in ["pemerintah", "kebijakan", "aturan"]):
        return "Pandangan Terhadap Pemerintah"
    if any(k in kw for k in ["bohong", "tipu", "jahat"]):
        return "Ketidakpercayaan / Sikap Skeptis"
    if any(k in kw for k in ["lucu", "sarkas", "komedi"]):
        return "Humor / Sarkasme"

    return "Persepsi Umum / Tidak Terdefinisi"

"""**TAHAP 13 — Menggabungkan Semuanya → Interpretasi Lengkap Setiap Cluster**"""

def interpret_cluster(cluster_id):
    print("="*50)
    print(f" CLUSTER {cluster_id}")
    print("="*50)

    # 1. Kata kunci
    keywords = get_top_keywords(cluster_id)
    print("\n🔹 Kata Kunci Dominan:")
    print(keywords)

    # 2. Topik persepsi
    topic = label_topic(keywords)
    print("\n🔹 Topik Persepsi Utama:")
    print(topic)

    # 3. Komentar representatif
    reps = get_representative_comments(cluster_id)
    print("\n🔹 Contoh Komentar Representatif:")
    for r in reps:
        print("-", r)


for c in clusters:
    if c != -1:
        interpret_cluster(c)

"""## VISUALISASI TOPIK PER CLUSTER"""

import numpy as np

cluster_centroids = {}

for cluster_id in df["cluster"].unique():
    if cluster_id == -1:  # skip noise
        continue
    idx = df[df["cluster"] == cluster_id].index.tolist()
    cluster_centroids[cluster_id] = umap_embeddings[idx].mean(axis=0)

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(12, 8))


scatter = plt.scatter(
    df[UMAP_2D_COLS[0]],
    df[UMAP_2D_COLS[1]],
    c=df["cluster"],
    cmap="tab20",
    s=20
)

plt.title("Visualisasi Cluster Persepsi Masyarakat (UMAP + HDBSCAN)")
plt.xlabel("UMAP Dimensi 1")
plt.ylabel("UMAP Dimensi 2")


cluster_centroids = {}
for cluster_id in sorted(df["cluster"].unique()):
    if cluster_id == -1:
        continue

    cluster_umap_coords = df[df["cluster"] == cluster_id][list(UMAP_2D_COLS)].values
    if len(cluster_umap_coords) > 0:
        cluster_centroids[cluster_id] = cluster_umap_coords.mean(axis=0)

# Tambah label topik
for cluster_id, centroid in cluster_centroids.items():
    keywords = get_top_keywords(cluster_id)
    topic_label = label_topic(keywords)

    plt.text(
        centroid[0],
        centroid[1],
        f"Cluster {cluster_id}\n{topic_label}",
        fontsize=9,
        weight="bold",
        bbox=dict(facecolor='white', alpha=0.7, edgecolor="black")
    )

plt.colorbar(scatter)
plt.show()

"""## **WORDCLOUD PER CLUSTER**"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_wordcloud(cluster_id):
    text = " ".join(df[df["cluster"] == cluster_id]["clean_text"].tolist())

    wc = WordCloud(
        width=1200,
        height=800,
        background_color="white",
        collocations=False
    ).generate(text)

    plt.figure(figsize=(10, 7))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")

    keywords = get_top_keywords(cluster_id)
    topic_label = label_topic(keywords)

    plt.title(f"Wordcloud Cluster {cluster_id} — {topic_label}", fontsize=14)
    plt.show()

for c in df["cluster"].unique():
    if c != -1:
        generate_wordcloud(c)